# Generated by Django 4.1.5 on 2023-01-23 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=8)),
                ('number', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128)),
                ('short', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('allow_subgroup', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('patronymic', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField()),
                ('begin', models.TimeField()),
                ('end', models.TimeField()),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.SmallIntegerField()),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('subject', models.CharField(max_length=32)),
                ('auditorium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.auditorium')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.group')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.tutor')),
            ],
        ),
        migrations.AddField(
            model_name='auditorium',
            name='corp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.campus'),
        ),
    ]
