# Generated by Django 4.1.5 on 2023-01-23 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='num',
            new_name='number',
        ),
    ]
